version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${DATA_DIR:-./data}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    command: [ "/app/sh/startup.sh" ]
    restart: unless-stopped
    depends_on:
      - ollama
      - postgres
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REMOTE_POSTGRES_HOST=${REMOTE_POSTGRES_HOST:-}
      - REMOTE_POSTGRES_PORT=${REMOTE_POSTGRES_PORT:-5432}
      - REMOTE_POSTGRES_USER=${REMOTE_POSTGRES_USER:-}
      - REMOTE_POSTGRES_PASSWORD=${REMOTE_POSTGRES_PASSWORD:-}
      - REMOTE_POSTGRES_DB=${REMOTE_POSTGRES_DB:-}
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1:70b}

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    volumes:
      # Mount from host directory specified in .env
      - ${OLLAMA_MODELS_DIR:-./ollama-models}:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    # Add GPU support via NVIDIA Container Toolkit
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:11434/ || exit 0" ]
      interval: 120s
      timeout: 60s
      retries: 3
      start_period: 300s

networks:
  app-network:
    driver: bridge
